name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //...
      - run: bazel test //... --test_output=all 
      - run: pwd
  
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: ci
    runs-on: ubuntu-latest
    if: always()

    steps:
      - run: ls -l 
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        
        with:
          path: ../../../.cache/**/*.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
      
      
