name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //...
      - run: bazel test //...
      - run: pwd
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      
