name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build //...
      - run: bazel test //... --test_output=all 
      - run: pwd

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: 'my-artifact'
          path: ../../../.cache/

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: my-artifact
      
      
